### PR TITLE
Add Jekyll integration + Bootstrap 4

### LINKED ISSUE #1: static site generator?
which static site generator to use and how to structure the content

### PR DESCRIPTION
**Pull request by jeroendesloovere**
## Pull request description

Fixes https://github.com/dockerwest/dockerwest.github.io/issues/1
> Jekyll is the number one supported static site generator for Github Pages.

## Changes
- Remove lots of duplicate content (header, footer, navbar, ...) by using Jekyll
- Use external bootstrap instead of /components/bootstrap
- Use external jquery instead of /components/jquery
- Use bootstrap 4 instead of 3

## Result

You can view the result over here: https://jeroendesloovere.github.io/dockerwest.github.io
The layout is practically identical to the one you guys now have.
schermafbeelding 2018-05-16 om 16 01 00

## Note

I have not touched any of the code you guys wrote.
Just converted it into a Jekyll site.

### CODE REVIEW

**Comment by jeroendesloovere** [comment]
If there are any questions, I'd be happy to answer them.

Note: you can view the result over here: https://jeroendesloovere.github.io/dockerwest.github.io

**Comment by BlackIkeEagle** [comment]
Thanks, but in the drafts branch we use sculpin and just publish the generated html to master.

Its still worth looking into jeckyll if that would reduce the steps needed to add something to the site.

**Comment by BlackIkeEagle** [comment]
Does it provide an rss feed? I see the atom.xml is not changed by the jekyll change

**Comment by jeroendesloovere** [comment]
Hi @BlackIkeEagle,

Thanks for taking the time to answer my PR.
It was my first experience with Jekyll and thought it was fun to convert your project to it.

1. I did not know you were already using a static site generator and did not notice the `drafts` branch. To me, it seems faster to just having the "source" files in "master" branch - and let Github compile everything (local compiling is also possible very easily) - seems like a faster way of working... Don't you agree?
2. Currently I did not touch the RSS feed, but indeed, it would be nice if that should be created automatically. That is possible using one of these:
* https://github.com/jekyll/jekyll-feed
* https://github.com/assafgelber/jekyll-rss
* ...

Questions from my part if you want me to finish the PR:
* I assume the blog directory can be removed entirely?

Otherwise, it was a nice project for learning Jekyll.
Which is actually pretty easy to use.

**Comment by BlackIkeEagle** [comment]
We might want to do blogs in the future, but currently there is nothing there :)

I'll discuss it if we possibly want to switch to jekyll from sculpin or not. I'll let you know

**Comment by BlackIkeEagle** [comment]
If you have the time, you can finish this. If the feeds are also available it would be great.

**Comment by jeroendesloovere** [comment]
Done

**Review by BlackIkeEagle — APPROVED** [review]

**Pull request merged**
